config/routes.rb
=begin
Copyright 2013 WBEZ
This file is part of Curious City.

Curious City is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

Curious City is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with Curious City.  If not, see <http://www.gnu.org/licenses/>.
=end
Curiouscity::Application.routes.draw do
  root  'voting_rounds#home'
  match '/about', to: 'voting_rounds#about', via: 'get'
  match '/ask_question', to: 'questions#new',     via: 'post'
  match '/confirm_question', to: 'questions#confirm', via: 'post'
  match '/vote', to: 'voting_rounds#vote', via: 'post'
  match '/vote_widget', to: 'widget#vote_widget', via: 'get'
  match '/widget_vote', to: 'widget#vote', via: 'post'
  match '/IE8_ask_widget', to: 'widget#IE8_ask_widget', via: 'get'
  match '/ask_widget', to: 'widget#ask_widget', via: 'get'
  match '/picture_question', to: 'questions#picture', via: 'post'
  match '/find_pictures', to: 'questions#find_pictures', via: 'post'
  match '/questions/:status(/:category_name)', to: 'questions#filter', via: 'get', as: 'filter_questions', constraints: { status: /answered|archive/}
  match '/admin/questions/tag/:tag', to: 'admin/questions#filter_by_tag', via: 'get', as: 'filter_admin_questions'
  match '/admin/questions/search/', to: 'admin/questions#search', via: 'post', as: 'search_admin_questions'
  match '/search', to: 'questions#search', via: 'get', as: 'search_user_questions'
  match '/ask_mobile', to: 'questions#ask_mobile', via: 'get', as: 'ask_mobile'
  match '/submit_mobile', to: 'questions#submit_mobile', via: 'post', as: 'submit_mobile'
  match '/confirm_mobile', to: 'questions#confirm_mobile', via: 'get', as: 'confirm_mobile'
  resources :questions, only: [:create, :new, :show]
  resources :voting_rounds, only: [:show]

  namespace :admin do
    resources :categories do
      member do
        post :deactivate
        post :activate
      end
    end
    resources :voting_round_questions
    resources :voting_rounds, except: [:destroy] do
      member do
        post :add_question
        post :remove_question
      end
    end
    resources :users
    resources :sessions, only: [:new, :create, :destroy]
    resources :questions do
      member do
        post :add_question_to_voting_round
      end
    end
    resources :answers do
      collection do
        get :reorder
        post :sort
      end
    end

    match '/signup',       to: 'users#new',        via: 'get'
    match '/signin',       to: 'sessions#new',      via: 'get'
    match '/signout',      to: 'sessions#destroy',  via: 'delete'
  end

  match '/admin',   to: 'admin/users#main',       via: 'get'
end

app/models/answer.rb
=begin
Copyright 2013 WBEZ
This file is part of Curious City.

Curious City is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

Curious City is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with Curious City.  If not, see <http://www.gnu.org/licenses/>.
=end
class Answer < ActiveRecord::Base
  belongs_to :question
  acts_as_list :scope => :question

  validates :label, length: { maximum: 3000, minimum: 1 }
  validates :url, length: { maximum: 2000, minimum: 1 }
  validates :type, presence: true
  self.inheritance_column = :_type_disabled

  def self.recent_answers
    where(type: "Answer").order(updated_at: :desc).limit(10)
  end

  def self.recent_updates
    where(type: "Update").order(updated_at: :desc).limit(10)
  end

  module Type
    Answer = "Answer"
    Update = "Update"
    All = [Answer, Update]
  end
end

app/controllers/admin/answers_controller.rb
=begin
Copyright 2013 WBEZ
This file is part of Curious City.

Curious City is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

Curious City is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with Curious City.  If not, see <http://www.gnu.org/licenses/>.
=end
module Admin
  class AnswersController < Admin::AdminController
    before_action :load_answers_and_updates, only: [:index, :destroy, :reorder]
    before_action :admin_privilege_check, only: [:edit, :new, :reorder, :destroy]

    def index
      @question = Question.find(params[:question_id])
    end

    def edit
        @answer = Answer.find(params[:id])
    end

    def update
      @answer = Answer.find(params[:id])
      if @answer.update_attributes(answer_params)
        redirect_to(admin_answers_url(question_id: params[:answer][:question_id]))
      else
        render "edit"
      end
    end

    def new
        params.require(:question_id)
        @answer = Answer.new(question_id: params[:question_id])
    end

    def reorder
    end

    def sort
      params[:answer].each_with_index do |id, index|
        Answer.find(id).insert_at(index+1)
      end
      render nothing: true
    end

    def create
      @answer = Answer.new(answer_params)
      if @answer.save
        redirect_to(admin_answers_url(question_id: @answer.question_id))
      else
        render "new"
      end
    end

    def destroy
        answer = Answer.find(params[:id])
        @question = Question.find(params[:question_id])
        answer.destroy
        render "index"
    end

    private
      def load_answers_and_updates
        params.require(:question_id)
        ordered_answers_both_types = Question.find(params[:question_id]).answers.order(:position)
        @answers = ordered_answers_both_types.where(type: Answer::Type::Answer)
        @updates = ordered_answers_both_types.where(type: Answer::Type::Update)
      end

      def answer_params
        params.require(:answer).permit(:label, :url, :question_id, :type)
      end
  end
end

app/views/admin/answers/edit.html.erb
<!--Copyright 2013 WBEZ
This file is part of Curious City.

Curious City is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

Curious City is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with Curious City.  If not, see <http://www.gnu.org/licenses/>.!-->
<% provide(:title, 'Edit Answer') %>

<h1>Edit answer</h1>

<%= form_for(@answer, :url => admin_answer_path(question_id: @answer.question_id)) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |msg| %>
        <li class="error-message"><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :label %><br>
    <%= f.text_area :label, size: "100x10" %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_area :url, size: "100x3" %>
  </div>
  <div class="field">
    <%= f.hidden_field :question_id, value: @answer.question_id %>
  </div>
  <div class="field">
    <%= f.radio_button :type, Answer::Type::Answer %>
    <%= f.label :type, 'Answer', value: Answer::Type::Answer %>
    <%= f.radio_button :type, Answer::Type::Update %>
    <%= f.label :type, 'Update', value: Answer::Type::Update %>
  </div>
  <%= f.submit "Update Answer", class: "btn btn-default" %> 
<% end %>

app/views/admin/answers/index.html.erb
<!--Copyright 2013 WBEZ
This file is part of Curious City.

Curious City is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

Curious City is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with Curious City.  If not, see <http://www.gnu.org/licenses/>.!-->
<% provide(:title, 'Listing Answers and Updates') %>
<h1>Listing answers</h1>

<table class="table">
  <thead>
    <tr>
      <th>Label</th>
      <th>Url</th>
      <th>Type</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr class="answer-row">
        <td class="answer-label">
          <%= answer.label %>
        </td>
        <td class="answer-url">
          <%= answer.url %>
        </td>
        <td class="answer-type">
          <%= answer.type %>
        </td>
        <td class="answer-edit-link">
          <%= link_to 'Edit', edit_admin_answer_path(answer) %>
        </td>
        <td class="answer-delete-link">
          <%= link_to 'Delete', admin_answer_path(answer, question_id: answer.question_id), :method => :delete %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<h1>Listing updates</h1>

<table class="table">
  <thead>
    <tr>
      <th>Label</th>
      <th>Url</th>
      <th>Type</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @updates.each do |update| %>
      <tr class="update-row">
        <td class="update-label">
          <%= update.label %>
        </td>
        <td class="update-url">
          <%= update.url %>
        </td>
        <td class="update-type">
          <%= update.type %>
        </td>
        <td class="update-edit-link">
          <%= link_to 'Edit', edit_admin_answer_path(update) %>
        </td>
        <td class="update-delete-link">
          <%= link_to 'Delete', admin_answer_path(update, question_id: update.question_id), :method => :delete %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Reorder Answers and Updates', reorder_admin_answers_path(question_id: @question.id), class: "btn-default btn" %>
<%= link_to 'New Answer or Update', new_admin_answer_path(question_id: @question.id), class: "btn-default btn" %>

app/views/admin/answers/new.html.erb
<!--Copyright 2013 WBEZ
This file is part of Curious City.

Curious City is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

Curious City is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with Curious City.  If not, see <http://www.gnu.org/licenses/>.!-->
<% provide(:title, 'New Answer') %>
<h1>New answer</h1>

<%= form_for(@answer, :url => admin_answers_path) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>
      <ul>
      <% @answer.errors.full_messages.each do |msg| %>
        <li class="error-message"><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :label %><br>
    <%= f.text_area :label, size: "100x10" %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_area :url, size: "100x3" %>
  </div>
  <div class="field">
    <%= f.hidden_field :question_id %>
  </div>
  <div class="field">
    <%= f.radio_button :type, Answer::Type::Answer %>
    <%= f.label :type, 'Answer', value: Answer::Type::Answer %>
    <%= f.radio_button :type, Answer::Type::Update %>
    <%= f.label :type, 'Update', value: Answer::Type::Update %>
  </div>
  <%= f.submit "Add answer to question", class: "btn btn-default" %> 
<% end %>

app/views/admin/answers/reorder.html.erb
<!--Copyright 2013 WBEZ
This file is part of Curious City.

Curious City is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

Curious City is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with Curious City.  If not, see <http://www.gnu.org/licenses/>.!-->
<%= javascript_include_tag "jquery.ui.sortable"%>
<% provide(:title, 'Listing Answers and Updates') %>
<script>
  $(function() {
    $("#sortable1").sortable({ 
      axis: 'y',
      update: function (event, ui) {
        var data = $(this).sortable("serialize");
        $.post($(this).data("update-url"), $(this).sortable("serialize"));
      }
    });
    $("#sortable2").sortable({ 
      axis: 'y',
      update: function (event, ui) {
        var data = $(this).sortable("serialize");
        $.post($(this).data("update-url"), $(this).sortable("serialize"));
      }
    });
  });
</script>
<p>Drag and drop to reorder.</p>
<h1>Reordering answers</h1>
<ul id="sortable1" data-update-url="<%= sort_admin_answers_url %>"> 
  <% @answers.each do |answer| %>
    <li class="ui-state-default" id="answer_<%= answer.id %>">
      <%= "#{answer.label} (" %>
      <%= link_to h(answer.url), answer.url %>
      <%= ")" %>
    </li>
  <% end %>
</ul>
<h1>Reordering updates</h1>
<ul id="sortable2" data-update-url="<%= sort_admin_answers_url %>">
  <% @updates.each do |update| %>
    <li class="ui-state-default" id="answer_<%= update.id %>">
      <%= "#{update.label} (" %>
      <%= link_to h(update.url), update.url %>
      <%= ")" %>
    </li>
  <% end %>
</ul>