config/routes.rb
=begin
Copyright 2013 WBEZ
This file is part of Curious City.

Curious City is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

Curious City is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with Curious City.  If not, see <http://www.gnu.org/licenses/>.
=end
Curiouscity::Application.routes.draw do
  root  'voting_rounds#home'
  match '/about', to: 'voting_rounds#about', via: 'get'
  match '/ask_question', to: 'questions#new',     via: 'post'
  match '/confirm_question', to: 'questions#confirm', via: 'post'
  match '/vote', to: 'voting_rounds#vote', via: 'post'
  match '/vote_widget', to: 'widget#vote_widget', via: 'get'
  match '/widget_vote', to: 'widget#vote', via: 'post'
  match '/IE8_ask_widget', to: 'widget#IE8_ask_widget', via: 'get'
  match '/ask_widget', to: 'widget#ask_widget', via: 'get'
  match '/picture_question', to: 'questions#picture', via: 'post'
  match '/find_pictures', to: 'questions#find_pictures', via: 'post'
  match '/questions/:status(/:category_name)', to: 'questions#filter', via: 'get', as: 'filter_questions', constraints: { status: /answered|archive/}
  match '/admin/questions/tag/:tag', to: 'admin/questions#filter_by_tag', via: 'get', as: 'filter_admin_questions'
  match '/admin/questions/search/', to: 'admin/questions#search', via: 'post', as: 'search_admin_questions'
  match '/search', to: 'questions#search', via: 'get', as: 'search_user_questions'
  match '/ask_mobile', to: 'questions#ask_mobile', via: 'get', as: 'ask_mobile'
  match '/submit_mobile', to: 'questions#submit_mobile', via: 'post', as: 'submit_mobile'
  match '/confirm_mobile', to: 'questions#confirm_mobile', via: 'get', as: 'confirm_mobile'
  resources :questions, only: [:create, :new, :show]
  resources :voting_rounds, only: [:show]

  namespace :admin do
    resources :categories do
      member do
        post :deactivate
        post :activate
      end
    end
    resources :voting_round_questions
    resources :voting_rounds, except: [:destroy] do
      member do
        post :add_question
        post :remove_question
      end
    end
    resources :users
    resources :sessions, only: [:new, :create, :destroy]
    resources :questions do
      member do
        post :add_question_to_voting_round
      end
    end
    resources :answers do
      collection do
        get :reorder
        post :sort
      end
    end

    match '/signup',       to: 'users#new',        via: 'get'
    match '/signin',       to: 'sessions#new',      via: 'get'
    match '/signout',      to: 'sessions#destroy',  via: 'delete'
  end

  match '/admin',   to: 'admin/users#main',       via: 'get'
end

app/models/category.rb
=begin
Copyright 2013 WBEZ
This file is part of Curious City.

Curious City is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

Curious City is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with Curious City.  If not, see <http://www.gnu.org/licenses/>.
=end
class Category < ActiveRecord::Base
  validates :name, format: {with: /\A[a-zA-Z\-]+\z/, message: "only allows dash and letters" }

  has_and_belongs_to_many :questions
end

app/controllers/admin/categories_controller.rb
=begin
Copyright 2013 WBEZ
This file is part of Curious City.

Curious City is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

Curious City is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with Curious City.  If not, see <http://www.gnu.org/licenses/>.
=end
class Admin::CategoriesController < Admin::AdminController
  before_action :set_admin_category, only: [:show, :edit, :update, :deactivate, :activate]
  before_action :admin_privilege_check, only: [:new, :edit, :deactivate, :activate]

  # GET /admin/categories
  def index
    @admin_categories = Category.all
  end

  # GET /admin/categories/1
  def show
  end

  # GET /admin/categories/new
  def new
    @admin_category = Category.new
  end

  # GET /admin/categories/1/edit
  def edit
  end

  # POST /admin/categories
  def create
    @admin_category = Category.new(admin_category_params)

    respond_to do |format|
      if @admin_category.save
        format.html { redirect_to admin_category_url(@admin_category), notice: 'Category was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH/PUT /admin/categories/1
  def update
    respond_to do |format|
      if @admin_category.update(admin_category_params)
        format.html { redirect_to admin_category_url(@admin_category), notice: 'Category was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  # POST /admin/categories/1
  def deactivate
    @admin_category.update_attribute(:active, false)
    respond_to do |format|
      format.html { redirect_to admin_categories_url }
    end
  end

  def activate
    @admin_category.update_attribute(:active, true)
    redirect_to admin_categories_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_category
      @admin_category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_category_params
      params.require(:admin_category).permit(:name, :label, :active)
    end
end

app/helpers/admin/categories_helper.rb
=begin
Copyright 2013 WBEZ
This file is part of Curious City.

Curious City is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

Curious City is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with Curious City.  If not, see <http://www.gnu.org/licenses/>.
=end
module Admin::CategoriesHelper
end

app/views/admin/categories/_form.html.erb
<!--Copyright 2013 WBEZ
This file is part of Curious City.

Curious City is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

Curious City is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with Curious City.  If not, see <http://www.gnu.org/licenses/>.!-->
<%= form_for(@admin_category, :as => :admin_category, :url => url) do |f| %>
  <% if @admin_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_category.errors.count, "error") %> prohibited this admin_category from being saved:</h2>

      <ul>
      <% @admin_category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :label %><br>
    <%= f.text_field :label %>
  </div>
  <div class="actions">
    <%= f.submit nil, class: "btn-default btn" %>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<!--Copyright 2013 WBEZ
This file is part of Curious City.

Curious City is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

Curious City is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with Curious City.  If not, see <http://www.gnu.org/licenses/>.!-->
<% provide(:title, 'Edit Category') %>
<h1>Edit category</h1>

<%= render 'form', :url => admin_category_path(@admin_category) %>

<%= link_to 'Show', admin_category_path(@admin_category) %> |
<%= link_to 'Back', admin_categories_path %>

app/views/admin/categories/index.html.erb
<!--Copyright 2013 WBEZ
This file is part of Curious City.

Curious City is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

Curious City is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with Curious City.  If not, see <http://www.gnu.org/licenses/>.!-->
<% provide(:title, 'Listing Categories') %>
<h1>Listing categories</h1>

<%= link_to 'New Category', new_admin_category_path, class:"btn-default btn" if current_admin? %>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Label</th>
      <th>Active</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_categories.each do |admin_category| %>
      <tr>
        <td><%= admin_category.name %></td>
        <td><%= admin_category.label %></td>
        <td class="active-label"><%= admin_category.active %></td>
        <td><%= link_to 'Show', admin_category_path(admin_category) %></td>
        <% if current_admin? %>
          <td><%= link_to 'Edit', edit_admin_category_path(admin_category) %></td>
          <% if admin_category.active %>
            <td><%= link_to 'Deactivate', deactivate_admin_category_path(admin_category), method: :post, data: { confirm: 'Are you sure?' } %></td>
          <% else %>
            <td><%= link_to 'Activate', activate_admin_category_path(admin_category), method: :post, class: "activate-link"  %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/categories/new.html.erb
<!--Copyright 2013 WBEZ
This file is part of Curious City.

Curious City is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

Curious City is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with Curious City.  If not, see <http://www.gnu.org/licenses/>.!-->
<% provide(:title, 'New Category') %>
<h1>New category</h1>

<%= render 'form', :url => admin_categories_path %>

<%= link_to 'Back', admin_categories_path %>

app/views/admin/categories/show.html.erb
<!--Copyright 2013 WBEZ
This file is part of Curious City.

Curious City is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

Curious City is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with Curious City.  If not, see <http://www.gnu.org/licenses/>.!-->
<% provide(:title, 'Show Category') %>

<p>
  <strong>Name:</strong>
  <%= @admin_category.name %>
</p>

<p>
  <strong>Label:</strong>
  <%= @admin_category.label %>
</p>

<p>
  <strong>Active:</strong>
  <%= @admin_category.active %>
</p>

<%= link_to 'Edit', edit_admin_category_path(@admin_category) %> |
<%= link_to 'Back', admin_categories_path %>