config/routes.rb
=begin
Copyright 2013 WBEZ
This file is part of Curious City.

Curious City is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

Curious City is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with Curious City.  If not, see <http://www.gnu.org/licenses/>.
=end
Curiouscity::Application.routes.draw do
  root  'voting_rounds#home'
  match '/about', to: 'voting_rounds#about', via: 'get'
  match '/ask_question', to: 'questions#new',     via: 'post'
  match '/confirm_question', to: 'questions#confirm', via: 'post'
  match '/vote', to: 'voting_rounds#vote', via: 'post'
  match '/vote_widget', to: 'widget#vote_widget', via: 'get'
  match '/widget_vote', to: 'widget#vote', via: 'post'
  match '/IE8_ask_widget', to: 'widget#IE8_ask_widget', via: 'get'
  match '/ask_widget', to: 'widget#ask_widget', via: 'get'
  match '/picture_question', to: 'questions#picture', via: 'post'
  match '/find_pictures', to: 'questions#find_pictures', via: 'post'
  match '/questions/:status(/:category_name)', to: 'questions#filter', via: 'get', as: 'filter_questions', constraints: { status: /answered|archive/}
  match '/admin/questions/tag/:tag', to: 'admin/questions#filter_by_tag', via: 'get', as: 'filter_admin_questions'
  match '/admin/questions/search/', to: 'admin/questions#search', via: 'post', as: 'search_admin_questions'
  match '/search', to: 'questions#search', via: 'get', as: 'search_user_questions'
  match '/ask_mobile', to: 'questions#ask_mobile', via: 'get', as: 'ask_mobile'
  match '/submit_mobile', to: 'questions#submit_mobile', via: 'post', as: 'submit_mobile'
  match '/confirm_mobile', to: 'questions#confirm_mobile', via: 'get', as: 'confirm_mobile'
  resources :questions, only: [:create, :new, :show]
  resources :voting_rounds, only: [:show]

  namespace :admin do
    resources :categories do
      member do
        post :deactivate
        post :activate
      end
    end
    resources :voting_round_questions
    resources :voting_rounds, except: [:destroy] do
      member do
        post :add_question
        post :remove_question
      end
    end
    resources :users
    resources :sessions, only: [:new, :create, :destroy]
    resources :questions do
      member do
        post :add_question_to_voting_round
      end
    end
    resources :answers do
      collection do
        get :reorder
        post :sort
      end
    end

    match '/signup',       to: 'users#new',        via: 'get'
    match '/signin',       to: 'sessions#new',      via: 'get'
    match '/signout',      to: 'sessions#destroy',  via: 'delete'
  end

  match '/admin',   to: 'admin/users#main',       via: 'get'
end

app/models/user.rb
=begin
Copyright 2013 WBEZ
This file is part of Curious City.

Curious City is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

Curious City is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with Curious City.  If not, see <http://www.gnu.org/licenses/>.
=end
class User < ActiveRecord::Base
  before_create :create_remember_token
  has_secure_password
  validates :username, uniqueness: true

  def self.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def self.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private
    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/admin/users_controller.rb
=begin
Copyright 2013 WBEZ
This file is part of Curious City.

Curious City is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

Curious City is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with Curious City.  If not, see <http://www.gnu.org/licenses/>.
=end
module Admin
  class UsersController < Admin::AdminController
    before_action :set_admin, only: [:show, :edit, :update, :destroy]
    before_action :load_page_info, only: [:main]
    before_action :admin_privilege_check, only: [:new, :edit, :destroy]

    # GET /admins
    def index
      @admins = User.all
    end

    # GET /admins/1
    def show
    end

    # GET /admins/new
    def new
      @admin = User.new
    end

    # GET /admins/1/edit
    def edit
    end

    # GET /admin_main
    def main
    end

    # POST /admins
    def create
      @admin = User.new(admin_params)

      respond_to do |format|
        if @admin.save
          format.html { redirect_to admin_users_url, notice: 'User was successfully created.' }
        else
          format.html { render action: 'new' }
        end
      end
    end

    # PATCH/PUT /admins/1
    def update
      respond_to do |format|
        if @admin.update(admin_params)
          format.html { redirect_to admin_users_url, notice: 'User was successfully updated.' }
        else
          format.html { render action: 'edit' }
        end
      end
    end

    # DELETE /admins/1
    def destroy
      @admin.destroy
      respond_to do |format|
        format.html { redirect_to admin_users_url }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_admin
        @admin = User.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def admin_params
        params.require(:admin).permit(:username, :password, :password_confirmation, :admin)
      end

      def load_page_info
        @recent_questions =  Question.recent_questions
        @recent_answers = Answer.recent_answers
        @recent_updates = Answer.recent_updates
        @recent_questions_with_updated_tags = Question.recent_questions_with_updated_tags
        @recent_questions_with_updated_notes = Question.recent_questions_with_updated_notes
        @voting_round = VotingRound.where(status: VotingRound::Status::Live).first
      end
  end
end

app/views/admin/users/_form.html.erb
<!--Copyright 2013 WBEZ
This file is part of Curious City.

Curious City is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

Curious City is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with Curious City.  If not, see <http://www.gnu.org/licenses/>.!-->
<%= form_for(@admin, :as => :admin, :url => url) do |f| %>
  <% if @admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:</h2>
      <ul>
      <% @admin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :admin, "Admin privileges?" %><br>
    <%= f.check_box :admin %>
  </div>
  <div class="actions">
    <%= f.submit nil, class: "btn-default btn" %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<!--Copyright 2013 WBEZ
This file is part of Curious City.

Curious City is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

Curious City is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with Curious City.  If not, see <http://www.gnu.org/licenses/>.!-->
<% provide(:title, 'Edit Admin') %>
<h1>Edit admin</h1>

<%= render 'form', :url => admin_user_path(@admin) %>

<%= link_to 'Show', admin_user_path(@admin) %> |
<%= link_to 'Back', admin_users_path %>

app/views/admin/users/index.html.erb
<!--Copyright 2013 WBEZ
This file is part of Curious City.

Curious City is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

Curious City is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with Curious City.  If not, see <http://www.gnu.org/licenses/>.!-->
<% provide(:title, 'Listing Admins') %>
<h1>Listing admins</h1>

<%= link_to 'New Admin', new_admin_user_path, class:"btn-default btn" if current_admin? %>

<table class="table">
  <thead>
    <tr>
      <th>Username</th>
      <th>Password</th>
      <th>Admin?</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @admins.each do |admin| %>
      <tr class="user-row">
        <td><%= admin.username %></td>
        <td><%= admin.password %></td>
        <td><%= admin.admin %></td>
        <td><%= link_to 'Show', admin_user_path(admin) %></td>
        <% if current_admin? %>
          <td><%= link_to 'Edit', edit_admin_user_path(admin) %></td>
          <td><%= link_to 'Destroy', admin_user_path(admin), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/users/main.html.erb
<!--Copyright 2013 WBEZ
This file is part of Curious City.

Curious City is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

Curious City is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with Curious City.  If not, see <http://www.gnu.org/licenses/>.!-->
<% provide(:title, 'Admin Home Page') %>
<h1>Admin Home Page</h1>

<div class="dashboard">
  <div class="row">
    <div class="recent-questions col-md-6">
      <details open>
      <summary><strong>Recent questions:</strong></summary>
      <table class="table table-bordered">
        <% @recent_questions.each_with_index do |question, i| %>
          <div class="recent-question"><tr><td>
                <%= link_to "#{i+1}. "+question.display_text, admin_question_path(question), target: "blank" %>
              </td></tr></div>
        <% end %>
      </table>
    </details>
  </div>
<div class="current-voting-round col-md-6">
  <details open>
  <summary><strong>Current Voting Round:</strong></summary>
  <%= render 'admin/shared/questions' %>
  </details>
</div>
</div>
<br>
<div class="row">
  <div class="recent-answers col-md-6">
    <details open>
    <summary><strong>Recent answers:</strong></summary>
    <table class="table table-bordered">
      <% @recent_answers.each_with_index do |answer, i| %>
        <div class="recent-answer"><tr><td>
          <%= link_to "#{i+1}. "+answer.label, admin_question_path(answer.question_id), target: "blank"  %> 
    </td></tr></div>
      <% end %>
    </table>
    </details>
  </div>
  <div class="recent-updates col-md-6">
    <details open>
    <summary><strong>Recent updates:</strong></summary>
    <table class="table table-bordered">
      <% @recent_updates.each_with_index do |update, i| %>
        <div class="recent-update"><tr><td>
          <%= link_to "#{i+1}. "+update.label, admin_question_path(update.question_id), target: "blank"  %> 
    </td></tr></div>
      <% end %>
    </table>
    </details>
  </div>
</div>
<br>
<div class="row">
  <div class="recent-tags col-md-6">
    <details open>
    <summary><strong>Recent tags:</strong></summary>
    <table class="table table-bordered">
      <% @recent_questions_with_updated_tags.each_with_index do |question, i| %>
        <div class="recent-tag"><tr><td>
          <%= link_to "#{i+1}. " + display_tags(question), admin_question_path(question), id: "tag", target: "blank"  %> 
    </td></tr></div>
      <% end %>
    </table>
    </details>
  </div>
  <div class="recent-notes col-md-6">
    <details open>
    <summary><strong>Recent notes:</strong></summary>
    <table class="table table-bordered">
      <% @recent_questions_with_updated_notes.each_with_index do |question, i| %>
        <div class="recent-note"><tr><td>
              <%= link_to "#{i+1}. "+question.notes, admin_question_path(question), target: "blank"  %> 
    </td></tr></div>
      <% end %>
    </table>
    </details>
  </div>
</div>
<br>

</div>

app/views/admin/users/new.html.erb
<!--Copyright 2013 WBEZ
This file is part of Curious City.

Curious City is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

Curious City is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with Curious City.  If not, see <http://www.gnu.org/licenses/>.!-->
<% provide(:title, 'New Admin') %>
<h1>New admin</h1>

<%= render 'form', :url => admin_users_path %>

<%= link_to 'Back', admin_users_path %>

app/views/admin/users/show.html.erb
<!--Copyright 2013 WBEZ
This file is part of Curious City.

Curious City is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

Curious City is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with Curious City.  If not, see <http://www.gnu.org/licenses/>.!-->
<% provide(:title, 'Show Admin') %>
<p>
  <strong>Username:</strong>
  <%= @admin.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @admin.password %>
</p>

<%= link_to 'Edit', edit_admin_user_path(@admin) %> |
<%= link_to 'Back', admin_users_path %>